### ISSUE TITLE
only gather fountains whose dissolved date (P576) is null || >> now()

### ISSUE THREAD

**Issue by ralfhauser** [mmmatthew/water-fountains.org#218]
https://www.wikidata.org/wiki/Q27229945
or rather https://h2o.do/ch-zh?l=de&i=Q27229945

<<20190513 hans.gonella@zuerich.ch: Im Rahmen der neuen Strassen-/Platzgestaltung entfernt und eingelagert bis ein neuer Standort gefunden wird. Näheres ist noch nicht bekannt.>>

**Comment by katjahenke** [comment]
Ahhhh... ich bin also doch nicht blind oder zu dämlich ;)

**Comment by ralfhauser** [comment]
Habe versucht dem WikiData item einen "comment" mit obigem Erklärungstext<<...>>> anzufügen, bin aber bei der "Reference" zum dissolved wie auch generellen "statements" gescheitert, ansonsten wäre es gut, dies in einem "discussion" oder ähnlichem Log zum Item festhalten zu können.

Latest try: https://www.wikidata.org/wiki/Q63866901

**Comment by ralfhauser** [comment]
Vielleicht müssen wir da eine neue Property (max 200 Characters freetext) im wikidata vorschlagen?

**Comment by ralfhauser** [comment]
if the filter is
![image](https://user-images.githubusercontent.com/1681677/57670700-b46b5c80-7610-11e9-91b4-4653548b3d5d.png),
it should be shown

**Comment by katjahenke** [comment]
Good morning

Just a few observations :
- Meyershof fountain (Niederdorf), while Julia and I have uploaded the photo, it does not show

- Drachenbrunnen in the garden of Villa Tobler, (as on Münsterhof Platz) two fountains are installed as one installation. But on Water-fountains.org they are listed as two separate installations (two dots) which is confusing for participating "photographers" as they upload photos of both fountains under one dot. JFYI - there are 3 fountains at Winkelwiese 4 as described in https://www.wikidata.org/wiki/Q23073407 and next to it also https://www.wikidata.org/wiki/Q55170437

- Ignaz-Heim Denkmal fountain (Heim Platz), this fountain does no longer exist (at least we were not able to find it)

Katja

**Comment by katjahenke** [comment]
Hi

Meyershof (https://commons.wikimedia.org/wiki/File:Brunnen_Meyershof_2.jpg) has been fixed. Please ignore the comment above.

Katja

**Comment by mmmatthew** [comment]
> Habe versucht dem WikiData item einen "comment" mit obigem Erklärungstext<<...>>> anzufügen, bin aber bei der "Reference" zum dissolved wie auch generellen "statements" gescheitert, ansonsten wäre es gut, dies in einem "discussion" oder ähnlichem Log zum Item festhalten zu können.

We could use the "cause of destruction" qualifier with the "road works" or "urban planning" value.
![image](https://user-images.githubusercontent.com/10126798/57771993-a0a91e80-7714-11e9-9f93-51296712d85e.png)

**Comment by ralfhauser** [comment]
Good idea. Done, but still doesn't allow to place a few specific words

**Comment by mmmatthew** [comment]
Summary of specifications:

- [ ] 1. Add additional property "removal_date" corresponding to the "dissolved" wikidata statement
- [ ] 2. By default, do not show removed fountains
- [ ] 3. Change date filter options to "existed in" and "built after" and add "show removed" tick box
- [ ] 4. If shown, display an icon where date, cause and explanation text can be shown “mouse-over”
![image](https://user-images.githubusercontent.com/10126798/57774084-def50c80-7719-11e9-8098-15c67c0bf992.png)

**Comment by ralfhauser** [comment]
another case https://www.wikidata.org/wiki/Q55166053

**Comment by ralfhauser** [comment]
thesaurus to more easily find this : disappeared, out of service ; no longer exists 

As per https://www.wikidata.org/wiki/Help:Qualifiers#Examples

end time (P582) (qualifier) → 1 September 1715 (qualifier value)

could be a solution

https://www.wikidata.org/wiki/Property:P582

**Comment by ralfhauser** [comment]
thesaurus: no-longer-existing , ceased , removed, dismantled

**Comment by ralfhauser** [comment]
see also https://github.com/water-fountains/proximap/issues/193
