### ISSUE TITLE
icon doesn't turn black despite osm 

### ISSUE THREAD

**Issue by ralfhauser** [mmmatthew/water-fountains.org#251]
as per https://github.com/water-fountains/proximap/issues/206#issuecomment-502350447

https://beta.water-fountains.org/ch-zh?l=de&i=Q55170911

![image](https://user-images.githubusercontent.com/1681677/59554844-d5c1be80-8fa9-11e9-8de5-dcf1f29e9f20.png)

even though 
![image](https://user-images.githubusercontent.com/1681677/59554853-f0943300-8fa9-11e9-851f-8c2e82ce6634.png)

**Comment by mmmatthew** [comment]
the issue here is that there is conflicting information: `amenity=drinking_water` and `drinking_water=no`.

Data extraction rules should be made more transparent and displayed in the property details view.

**Comment by ralfhauser** [comment]
ok, changed it to "amenity=fountain" like 
https://beta.water-fountains.org/ch-zh?l=en&i=Q27229673 
(Alfred Escher Brunnen)

**Comment by mmmatthew** [comment]
> ok, changed it to "amenity=fountain" like
> https://beta.water-fountains.org/ch-zh?l=en&i=Q27229673
> (Alfred Escher Brunnen)

It doesn't really look like a fountain to me. The following tag is more appropriate:
https://wiki.openstreetmap.org/wiki/Talk:Tag:man_made%3Dwater_tap

**Comment by mmmatthew** [comment]
I have fixed the processing in https://github.com/water-fountains/datablue/commit/6887c90eaa1194dd851f4a3da300531a1d9f777c, so that if `drinking_water=no`, then that trumps any inferred properties.

**Comment by FlipHaesli** [comment]
This still doesn't work for
https://www.openstreetmap.org/way/495224204  or https://www.wikidata.org/wiki/Q65095943 respectively

**Comment by mmmatthew** [comment]
@FlipHaesli what behavior were you expecting for the pond you refer to? I see the following, which seems reasonable:
![image](https://user-images.githubusercontent.com/10126798/60773320-f80baf80-a103-11e9-84d4-7736e974f733.png)
